SESSION :- 1
2) Create a new Jupyter Notebook file named analytics_intro.ipynb and write a cell that prints your name and your favorite app (like Instagram or Zomato) using the print() function.

In [ ]:
print("name :jiya")
print("app : printrest")

name :jiya
app : printrest


3) Open VS Code or any code editor, create a Python script file called hello_app.py, and write code to print 'Welcome to Data Analytics with Python!'. Then, run this script from the terminal.

In [ ]:
print("welcome to data analytics with python!!")

welcome to data analytics with python!!


4)  In Jupyter Notebook, add a new cell and write Python code to print the current year using the datetime module.<br><br><em><strong>Hint:</strong> Import datetime and use datetime.datetime.now().year.</em>

In [ ]:
import datetime

current_year = datetime.datetime.now().year
print("Current Year:", current_year)


Current Year: 2026


SESSION - 2
1) .Create three variables in Python: user_name, fav_app, and daily_usage_hours. Assign your own name, your favorite app (like Instagram or Zomato), and how many hours you use it daily.


In [ ]:
user_name="jiya"
fav_app="instagram"
daily_usagehours="3hours"
print("username :",user_name)
print("favorite app :",fav_app)
print("daily hours :",daily_usagehours)


username : jiya
favorite app : instagram
daily hours : 3hours


2) .Write a Python script that declares variables for product_name, price, and is_available to represent an item on Flipkart. Print each variable and its data type using the type() function.


In [ ]:
product_name="laptop"
price=50000
is_available="true"
print("product name :",product_name)
print("type :",type(product_name))
print("price :",price)
print("type :",type(price))
print("available :",is_available)
print("type :",type(is_available))


product name : laptop
type : <class 'str'>
price : 50000
type : <class 'int'>
available : true
type : <class 'str'>


3) .Demonstrate the difference between single-line and multi-line comments in Python by writing a script that explains how a Spotify playlist recommendation system might work. Use # for single-line and triple quotes for multi-line comments.


In [ ]:
#check the user's list
""" analyze spotify system and playlist 
the user likes to suggest similar music"""

print("generate user's playlists")

generate user's playlists


4) . Create variables for order_total, delivery_region, and discount_percent to represent a Zomato order. Follow Python naming conventions and print a sentence using all three variables, like 'Order from [region] totals ₹[order_total] with [discount_percent]% discount.




In [ ]:
order_total = 1000
delivery_region = "Ahmedabad"
discount_percent = 20

print(f"Order from {delivery_region} totals ₹{order_total} with {discount_percent}% discount.")

Order from Ahmedabad totals ₹1000 with 20% discount.


5) .Write a Python script that intentionally mixes tabs and spaces for indentation, then fix the script so it runs without errors.<br><br><em><strong>Hint:</strong> Use only spaces for indentation, as per Python's best practices.</em>

In [ ]:

a="num py"
print(a[0:5])
for i in a:
    print(i)

num p
n
u
m
 
p
y


SESSION :- 3
1) .Declare four variables in Python: one integer (number of followers), one float (average rating), one string (your favorite app's name), and one boolean (is_premium_user). Print each variable and its type using the type() function.

In [ ]:
numberof_followers=15
average_rating=2.5
app='instagram'
is_user='true'
print('followers:',numberof_followers)
print(type(numberof_followers))
print('rating:',average_rating)
print(type(average_rating))
print('app:',app)
print(type(app))
print('user available:',is_user)
print(type(is_user))

followers: 15
<class 'int'>
rating: 2.5
<class 'float'>
app: instagram
<class 'str'>
user available: true
<class 'str'>


2) .Write a Python program that takes a user's input for the price of a Zomato order as a string, converts it to a float using type casting, adds 18% GST, and prints the final bill amount.

In [ ]:
price = input("Enter the Zomato order price: ")

price = float(price)

gst = price * 0.18
final_bill = price + gst

print("Final bill amount:", final_bill)

Final bill amount: 594.72


3) .Given a list of strings representing product prices from Flipkart, like ['199.99', '299.50', '150'], convert all to floats and calculate the total cart value.

In [ ]:

price=['199.99', '299.50', '150']
float= [float(price) for price in price]
total=sum(float)
print('float price :',float)
print('total value :',total)

float price : [199.99, 299.5, 150.0]
total value : 649.49


4) .Build a function is_discount_applicable(order_amount) that takes a float and returns True if the amount is greater than 500, otherwise False. Print the result for order amounts 450 and 750.

In [ ]:
def discount(order_amount):
    return order_amount > 500

print(discount(450))
print(discount(750))

False
True


5) .You received a dataset of ratings as strings from Spotify: ['4.5', '3.0', '5', '4.2']. Use type casting to convert these to floats, then find and print the highest rating.<br><br><em><strong>Hint:</strong> Use the float() function inside a loop or list comprehension.</em>

In [ ]:
ratings = ['4.5', '3.0', '5', '4.2']
float_ratings=[float(rating)for rating in ratings]
high_rating = max(float_ratings)

print("Ratings:", float_ratings)
print("Highest Rating:", high_rating)

Ratings: [4.5, 3.0, 5.0, 4.2]
Highest Rating: 5.0


SESSION :-4

1) .Create a Python script that takes any product name string (e.g., 'Redmi Note 12 Pro') and prints the name in all uppercase and all lowercase using the upper() and lower() methods.

In [ ]:
name=input('enter name :')
print('uppercase :',name.upper())
print('lowercase :',name.lower())

uppercase : JIYA
lowercase : jiya



2) .Write a function clean_brand_name(name) that removes leading/trailing spaces and replaces any hyphens '-' with a single space in the input string. Test it with ' oneplus-Nord '.

In [ ]:
def clean_brand(name):
    return name.strip().replace('-',' ')
 
name='oneplus-nord'
print(clean_brand(name))

oneplus nord


3) .Given the string 'Apple iPhone 14 Pro Max', use string slicing to extract and print only the brand name and the model (i.e., 'Apple' and 'iPhone 14 Pro Max') separately.<br><br><em><strong>Hint:</strong> Use split() to help find the split point, then use slicing for the substrings.</em>

In [ ]:

product='apple iphone 14 pro max'
brand=product[:5]
model=product[6:]
print('brand :',brand)
print('model :',model)

brand : apple
model : iphone 14 pro max


4) .Build a function format_product_display(name, price) that takes a product name and price (e.g., 'Boat Earbuds', 1299) and returns a formatted string like 'Boat Earbuds - ₹1299'.

In [ ]:
def format_product_display(name,price):
    return{name}-{price}

print('product :','Boat Earbuds - ₹1299')

product : Boat Earbuds - ₹1299


5) .Suppose you have a list of messy product names: [' mi-Band 5 ', ' SAMSUNG-Galaxy ', ' realme-Book ']. Write code to clean each name (remove spaces, replace hyphens with spaces, and make the brand title case) and print the cleaned list.<br><br><em><strong>Constraint:</strong> Use at least three string methods from this session.</em>

In [ ]:

products=[' mi-Band 5 ', ' SAMSUNG-Galaxy ', ' realme-Book ']
clean_pro=[]
for product in products:
    product=product.strip()
    product=product.replace('-',' ')
    product=product.title()
    clean_pro.append(product)
print("product list :",clean_pro)

product list : ['Mi Band 5', 'Samsung Galaxy', 'Realme Book']


SESSION :- 5
1) .Create a list called playlist_ids with 5 integers representing Spotify playlist IDs, then use append() to add a new playlist ID at the end and print the updated list.

In [ ]:
playlist_ids = [101, 102, 103, 104, 105]

playlist_ids.append(106)

print(playlist_ids)

[101, 102, 103, 104, 105, 106]


2) .Simulate a Flipkart shopping cart: start with a list cart_items containing 't-shirt', 'shoes'. Use extend() to add ['jeans', 'cap'] to the cart, then print the final list of items.

In [ ]:
cart_items = ['t-shirt', 'shoes','tops']

cart_items.extend(['jeans', 'cap'])

print(cart_items)

['t-shirt', 'shoes', 'tops', 'jeans', 'cap']


3) .Write a function remove_last_item(order_list) that pops the last item from a Zomato order list and returns the removed item. Test it with a sample order_list.

In [ ]:
def lastitem(order_list):
    removeditem = order_list.pop()
    return removeditem


order_list = ['pizza', 'burger', 'cold drink']

removed = lastitem(order_list)

print("Removed item:", removed)
print("Updated order:", order_list)

Removed item: cold drink
Updated order: ['pizza', 'burger']


4) .Create a tuple called insta_filters with 4 Instagram filter names. Try to update the second filter and observe what error you get. Explain in a comment why this happens.<br><br><em><strong>Hint:</strong> Tuples are immutable, so direct assignment won't work.</em>

In [ ]:
insta_filters = ('Clarendon', 'Juno', 'Lark', 'Gingham')

try:
    insta_filters[1] = 'Valencia'
except TypeError as e:
    print("Error:", e)
# Error occurs because tuples are immutable.
# We cannot change, add, or remove  elements of a tuple.

Error: 'tuple' object does not support item assignment


5) .Given two scenarios — storing a user's favorite genres (which may change) and storing a fixed set of IRCTC train classes ('Sleeper', 'AC 3 Tier', 'AC 2 Tier') — choose whether to use a list or tuple for each. Write one sentence explaining your choice for both.

In [ ]:
favorite_genres = ['Pop', 'Rock', 'Bollywood']

train_classes = ('Sleeper', 'AC 3 Tier', 'AC 2 Tier')

print(favorite_genres)
print(train_classes)
 #List : because the user may add, remove, or change genres.
 #Tuple : because the set of classes is fixed and should not be changed.

['Pop', 'Rock', 'Bollywood']
('Sleeper', 'AC 3 Tier', 'AC 2 Tier')


SESSION :- 6
1) .Create a Python dictionary called playlist_prices with at least 5 key-value pairs where the key is a Spotify playlist name (as a string) and the value is the playlist's price (as an integer). Print the dictionary.

In [ ]:
playlist_prices = {
    "Workout Hits": 100,
    "Chill Vibes": 80,
    "Party Mix": 120,
    "Bollywood Hits": 90,
    "Romantic Songs": 70
}

print(playlist_prices)

{'Workout Hits': 100, 'Chill Vibes': 80, 'Party Mix': 120, 'Bollywood Hits': 90, 'Romantic Songs': 70}


2) .Write a function update_playlist_price(playlist, new_price) that updates the price of a given playlist in the playlist_prices dictionary. Test it by updating the price of any one playlist and printing the updated dictionary.

In [ ]:
def update_playlist_price(playlist, new_price):
    playlist_prices[playlist] = new_price


update_playlist_price("Workout Hits", 150)

print(playlist_prices)

{'Workout Hits': 150, 'Chill Vibes': 80, 'Party Mix': 120, 'Bollywood Hits': 90, 'Romantic Songs': 70}


3) .Remove a playlist from the playlist_prices dictionary using the del statement. Print the dictionary after deletion to confirm the change.

In [ ]:
del playlist_prices["Party Mix"]

print(playlist_prices)

{'Workout Hits': 150, 'Chill Vibes': 80, 'Bollywood Hits': 90, 'Romantic Songs': 70}


4) .Given two sets: set1 contains the names of restaurants you have ordered from on Zomato, and set2 contains the names of restaurants you have ordered from on Swiggy, find and print the union and intersection of these sets.<br><br><em><strong>Hint:</strong> Use the union() and intersection() methods of Python sets.</em>

In [ ]:
set1 = {"Dominos", "McDonalds", "Subway", "Pizza Hut"}
set2 = {"Subway", "Pizza Hut", "KFC", "Burger King"}

union_set = set1.union(set2)
intersection_set = set1.intersection(set2)

print("Union:", union_set)
print("Intersection:", intersection_set)

Union: {'KFC', 'Pizza Hut', 'Subway', 'McDonalds', 'Burger King', 'Dominos'}
Intersection: {'Pizza Hut', 'Subway'}


SESSION :- 7
1) .Write a Python script that checks if a user's entered age is 18 or above and prints 'Eligible for IPL ticket booking' if true, otherwise prints 'Not eligible'.

In [ ]:
age = int(input("Enter your age: "))

if age >= 18:
    print("Eligible for IPL ticket booking")
else:
    print("Not eligible")

Eligible for IPL ticket booking


2) .Create a Python program that takes the number of followers as input and uses if, elif, and else to print 'Micro Influencer' if followers < 10,000, 'Rising Star' if between 10,000 and 100,000, and 'Celebrity' if above 100,000.

In [ ]:
followers = int(input("Enter number of followers: "))

if followers < 10000:
    print("Micro Influencer")
elif followers <= 100000:
    print("Rising Star")
else:
    print("Celebrity")

Rising Star


3) .Build a Python script that asks the user for their Zomato order total and prints 'Apply Free Delivery' if total is above 299, 'Add more items for free delivery' if between 200 and 299, else 'Delivery charges apply'.

In [ ]:
total = float(input("Enter your Zomato order total: "))

if total > 299:
    print("Apply Free Delivery")
elif total >= 200:
    print("Add more items for free delivery")
else:
    print("Delivery charges apply")

Add more items for free delivery


4) .Write a Python program using nested if statements: take a user's entered Flipkart cart value and payment method ('UPI', 'Card', 'Cash'). If the cart value is above 1000 and payment method is 'UPI', print 'Eligible for 10% cashback'; if above 1000 and payment is not 'UPI', print 'Eligible for 5% cashback'; else print 'No cashback'.

In [ ]:
cart_value = float(input("Enter your Flipkart cart value: "))
paymethod = input("Enter payment method (UPI/Card/Cash): ")

if cart_value > 1000:
    if paymethod == "UPI":
        print("Eligible for 10% cashback")
    else:
        print("Eligible for 5% cashback")
else:
    print("No cashback")

No cashback


SESSION :- 8
1.
Create a Python list called order_amounts with the values [120, 250, 90, 310, 150]. Use a for loop to calculate and print the total order value.

In [ ]:
order_amounts = [120, 250, 90, 310, 150]

total = 0

for amount in order_amounts:
    total = total + amount

print("Total order value:", total)

Total order value: 920


2.
Given a list of cricket scores [45, 78, 102, 34, 67, 89], use a while loop to print each score until you reach a score above 100, then stop printing.

In [ ]:
scores = [45 ,78, 102, 34 , 67, 89]

i = 0

while i < len(scores):
    if scores[i] > 100:
        break

    print(scores[i])
    i += 1

45
78


3.
Simulate a Flipkart cart with a list of item prices [299, 499, 199, 999, 149]. Use a for loop and the continue statement to skip any item priced below 200, and print the total of the remaining items.

In [ ]:
item_prices = [299, 499, 199, 999, 149]

total = 0

for price in item_prices:
    if price < 200:
        continue

    total = total + price

print("Total of remaining items:", total)

Total of remaining items: 1797


4.
You have a list of favorite song names: ['Kesariya', 'Believer', 'Shape of You', 'Blinding Lights', 'Excuses']. Use the enumerate() function in a for loop to print each song with its playlist position (starting from 1).

In [ ]:
songs = ['Kesariya', 'Believer', 'Shape of You', 'Blinding Lights', 'Excuses']

for position, song in enumerate(songs, start=1):
    print(position, song)

1 Kesariya
2 Believer
3 Shape of You
4 Blinding Lights
5 Excuses


5.
Write a for loop that goes through a list of Instagram follower counts [120, 1500, 23000, 800, 45000] and prints 'Micro', 'Influencer', or 'Celebrity' for each, based on the following: Micro (<1000), Influencer (1000-10000), Celebrity (>10000).<br><br><em><strong>Hint:</strong> Use if-elif-else inside the loop to check the follower count range.</em>

In [ ]:
followers = [120, 1500, 23000, 800, 45000]

for count in followers:
    if count < 1000:
        print("Micro")
    elif count <= 10000:
        print("Influencer")
    else:
        print("Celebrity")

Micro
Influencer
Celebrity
Micro
Celebrity


SESSION : - 9
1.
Define a function called calculate_final_price(price, discount_rate) that returns the final price after applying the discount. Test it with price 1200 and discount_rate 0.15.

In [ ]:
def calculate_final_price(price, discount_rate):
    discount = price * discount_rate
    final_price = price - discount
    return final_price


result = calculate_final_price(1200, 0.15)

print("Final price:", result)

Final price: 1020.0


2.
Create a function get_delivery_charge(amount, city='Ahmedabad') that returns a delivery charge: Rs. 30 for Ahmedabad, Rs. 50 for other cities. Call it with and without the city argument to see both results.

In [ ]:
def get_delivery_charge(amount, city='Ahmedabad'):
    if city == 'Ahmedabad':
        return 30
    else:
        return 50


print("Ahmedabad delivery charge:", get_delivery_charge(500))
print("suart delivery charge:", get_delivery_charge(500, 'surat'))

Ahmedabad delivery charge: 30
suart delivery charge: 50



3.
Build a function called format_coupon_message(username, discount=10) that returns a string like 'Hi Rahul, you get 10% off!' If no discount is given, use 10% by default. Test it for two users: one with a custom discount, one with the default.

In [ ]:
def format_coupon_message(username, discount=10):
    return f"Hi {username}, you get {discount}% off!"


print(format_coupon_message("Rahul", 20))
print(format_coupon_message("Priya"))

Hi Rahul, you get 20% off!
Hi Priya, you get 10% off!


4.
Given a function apply_discount(price, rate=0.10), update it so that if the rate is not passed, it uses 0.10 by default. Then, call it with only the price argument and print the result.<br><br><em><strong>Hint:</strong> Use default arguments in your function definition.</em>

In [ ]:
def apply_discount(price, rate=0.10):
    discount = price * rate
    final_price = price - discount
    return final_price


result = apply_discount(1000)

print("Final price:", result)

Final price: 900.0


5.
Write a function called calculate_cashback(amount, cashback_rate=0.05) that returns the cashback amount. Then, use it to calculate cashback for a Zomato order of Rs. 500 with the default rate, and for a Flipkart order of Rs. 2000 with a 7% cashback.

In [ ]:
def calculate_cashback(amount, cashback_rate=0.05):
    return amount * cashback_rate


zomato_cashback = calculate_cashback(500)

flipkart_cashback = calculate_cashback(2000, 0.07)

print("Zomato cashback:", zomato_cashback)
print("Flipkart cashback:", flipkart_cashback)

Zomato cashback: 25.0
Flipkart cashback: 140.0


SESSION :- 12
1.
Write a lambda function that takes a price in rupees and returns the price after adding 18% GST. Test it on the prices 100, 250, and 500.

In [ ]:
gst_price = lambda price: price + (price * 0.18)

print(gst_price(100))
print(gst_price(250))
print(gst_price(500))

118.0
295.0
590.0


2.
Given a list of song titles from Spotify with extra spaces and inconsistent casing, use map() and a lambda function to clean each title so that it is stripped of spaces and converted to title case (e.g., ' shape OF you ' → 'Shape Of You').

In [ ]:
songs = [' shape OF you ', 'senorita', 'BELIEVER ', 'mashup  ']

clean_songs = list(map(lambda song: song.strip().title(), songs))

print(clean_songs)

['Shape Of You', 'Senorita', 'Believer', 'Mashup']


3.
Use filter() and a lambda function to extract only those Flipkart product names from a list that start with the letter 'S' (case-insensitive).

In [ ]:
products = ['Shoes', 'T-Shirt', 'Smartphone', 'Laptop', 'Sunglasses', 'Watch']

s_products = list(filter(lambda product: product.lower().startswith('s'), products))

print(s_products)

['Shoes', 'Smartphone', 'Sunglasses']



4.
Given a list of order amounts from a Zomato cart [120, 340, 560, 80], use reduce() from functools to calculate the total bill amount.

In [ ]:
from functools import reduce

order_amounts = [120, 340, 560, 80]

total_bill = reduce(lambda x, y: x + y, order_amounts)

print("Total bill:", total_bill)

Total bill: 1100


5.
Use ChatGPT or Copilot to generate a Python code snippet that uses map(), filter(), and reduce() together to process a list of numbers: first double each number, then filter to keep only numbers greater than 100, and finally sum the result. Paste and test the generated code with the list [40, 60, 80, 120].

In [ ]:
from functools import reduce

numbers = [40, 60, 80, 120]

#  Double each number
doubled = list(map(lambda x: x * 2, numbers))

#  Keep numbers greater than 100
filtered = list(filter(lambda x: x > 100, doubled))

#  Calculate the sum
result = reduce(lambda x, y: x + y, filtered)

print("Doubled:", doubled)
print("Filtered:", filtered)
print("Final sum:", result)

Doubled: [80, 120, 160, 240]
Filtered: [120, 160, 240]
Final sum: 520


SESSION :- 13
1.
Write a recursive function in Python called reverse_string(s) that takes a string and returns it reversed (e.g., 'hello' becomes 'olleh').

In [ ]:
def reverse_string(s):

    if len(s) == 0:
        return s
    return reverse_string(s[1:]) + s[0]


print(reverse_string("hello"))

olleh


2.
Build a recursive function sum_playlist_durations(durations) that takes a list of song durations (in seconds) and returns the total duration, similar to how Spotify totals a playlist.

In [ ]:
def sum_playlist_durations(durations):
    # Base case
    if len(durations) == 0:
        return 0
    
    # Add first duration and call function for remaining durations
    return durations[0] + sum_playlist_durations(durations[1:])


playlist = [180, 240, 200, 300]

print("Total duration:", sum_playlist_durations(playlist), "seconds")

Total duration: 920 seconds


3.
Given the following code, identify whether the variable 'count' is local or global in each function, and explain what will be printed when run:

count = 10
def update_count():
count = 5
print('Inside:', count)

update_count()
print('Outside:', count)

In [ ]:
count = 10

def update_count():
    count = 5
    print("Inside:", count)


update_count()
print("Outside:", count)

Inside: 5
Outside: 10


4.
Create a recursive function count_likes(posts) that takes a nested dictionary representing Instagram posts and their replies (each with a 'likes' key), and returns the total number of likes across all posts and replies.<br><br><em><strong>Hint:</strong> Each reply can itself have more replies, so use recursion to sum likes at all levels.</em>

5.
Write a Python script that demonstrates the lifetime of a local variable inside a function versus a global variable by printing their values before, during, and after a function call. Use variable names similar to 'user_status' and 'app_status', inspired by WhatsApp online/offline status.

In [ ]:
# Global variable
app_status = "Offline"

print("Before function call:")
print("App status:", app_status)


def update_status():
    # Local variable
    user_status = "Online"

    print("\nDuring function call:")
    print("User status:", user_status)
    print("App status:", app_status)


update_status()

print("\nAfter function call:")
print("App status:", app_status)


Before function call:
App status: Offline

During function call:
User status: Online
App status: Offline

After function call:
App status: Offline


SESSION :- 14

1.
Use open() in write mode to create a file called my_playlist.txt and write the names of 5 songs you listened to this week, each on a new line.

In [ ]:

with open("my_playlist.txt", "w") as file:
    file.write("Perfect\n")
    file.write("Shape of You\n")
    file.write("Believer\n")
    file.write("Until I Found You\n")
    file.write("Tum Hi Ho\n")
print("Playlist created successfully!")

Playlist created successfully!


2.
Read the my_playlist.txt file you created and print each song name in uppercase using Python file handling.

In [ ]:

with open("my_playlist.txt", "r") as file:
    for song in file:
        print(song.strip().upper())

PERFECT
SHAPE OF YOU
BELIEVER
UNTIL I FOUND YOU
TUM HI HO


3.
Download a sample CSV file of IPL cricket match scores (or create your own with columns: Match, Team1, Team2, Winner), then write Python code to read the CSV and print the name of the winning team for each match.

In [ ]:
import csv

with open("ipl_matches.csv", "r") as file:
    reader = csv.DictReader(file)

    for row in reader:
        print(row["Winner"])

4.
Given a JSON file named user_profile.json containing details like username, followers, and bio (similar to an Instagram profile), use the json module to load the file and print the username and number of followers.

In [ ]:
import json

with open("user_profile.json", "r") as file:
    data = json.load(file)

print("Username:", data["username"])
print("Followers:", data["followers"])

5.
Use pathlib to check if a file called zomato_orders.json exists in your current directory, and print an appropriate message if it is found or not.<br><br><em><strong>Hint:</strong> Use Path('zomato_orders.json').exists() from the pathlib module.</em>

In [ ]:
from pathlib import Path

file_path = Path("zomato_orders.json")

if file_path.exists():
    print("zomato_orders.json file is found.")
else:
    print("zomato_orders.json file is not found.")

zomato_orders.json file is not found.


SESSION :- 15
1.
Write a Python function safe_divide(a, b) that returns the result of a divided by b, and handles ZeroDivisionError by returning the string 'Cannot divide by zero'.

In [ ]:
def safe_divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return "Cannot divide by zero"


print(safe_divide(10, 2))
print(safe_divide(10, 0))

5.0
Cannot divide by zero


2.
Simulate a Zomato-style rating system: ask the user for number of reviews and total stars, then calculate average rating. Use try-except to handle invalid (non-numeric) input and print an error message if input is not a number.<br><br><em><strong>Hint:</strong> Use input() and int() conversion inside a try block.</em>

In [ ]:
try:
    reviews = int(input("Enter number of reviews: "))
    total_stars = int(input("Enter total stars: "))

    average_rating = total_stars / reviews

    print("Average Rating:", average_rating)

except ValueError:
    print("Error: Please enter numbers only.")

Average Rating: 1.0


3.
Create a function get_playlist_duration(songs) that takes a list of song durations (in seconds) and returns the total duration in minutes. Raise a custom exception InvalidDurationError if any duration in the list is negative.<br><br><em><strong>Hint:</strong> Define your own exception class by subclassing Exception.</em>

In [1]:
class InvalidDurationError(Exception):
    pass


def get_playlist_duration(songs):
    total_seconds = 0

    for duration in songs:
        if duration < 0:
            raise InvalidDurationError("Song duration cannot be negative.")

        total_seconds += duration

    total_minutes = total_seconds / 60
    return total_minutes


try:
    songs = [180, 240, 300, 200]
    print("Playlist Duration:", get_playlist_duration(songs), "minutes")

except InvalidDurationError as e:
    print("Error:", e)

Playlist Duration: 15.333333333333334 minutes


4.
Build a Flipkart-style order summary: ask the user for item price and quantity, then calculate and print total price. Use try-except-else-finally blocks to handle ValueError for invalid input, print the total if successful, and always print 'Thank you for shopping!' in the finally block.

In [2]:
try:
    price = float(input("Enter item price: ₹"))
    quantity = int(input("Enter quantity: "))

    total_price = price * quantity

except ValueError:
    print("Error: Please enter valid numbers.")

else:
    print("Total Price: ₹", total_price)

finally:
    print("Thank you for shopping!")

Total Price: ₹ 1500.0
Thank you for shopping!


5.
Use ChatGPT or Copilot to generate a Python code snippet that asks for two numbers and divides them, handling both ZeroDivisionError and ValueError. Paste the generated code, run it, and write one line about what you learned from the AI's approach.

In [3]:
try:
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))

    result = num1 / num2

    print("Result:", result)

except ValueError:
    print("Error: Please enter valid numbers.")

except ZeroDivisionError:
    print("Error: Cannot divide by zero.")

Result: 0.625


SESSION :- 16
1.
Use iter() and next() to manually loop through a list of 5 trending movies from BookMyShow and print each movie name one by one.

In [4]:
movies = [
    "Avatar 3",
    "Pushpa 2",
    "Stree 2",
    "Jawan",
    "Animal"
]

movie_iterator = iter(movies)

print(next(movie_iterator))
print(next(movie_iterator))
print(next(movie_iterator))
print(next(movie_iterator))
print(next(movie_iterator))

Avatar 3
Pushpa 2
Stree 2
Jawan
Animal


2.
Create a playlist of 6 songs (as a list of strings) and use enumerate() to print each song with its position like Spotify's tracklist (e.g., '1. Kesariya').

In [5]:
songs = [
    "Kesariya",
    "Apna Bana Le",
    "Tum Hi Ho",
    "Chaleya",
    "Heeriye",
    "O Maahi"
]

for position, song in enumerate(songs, start=1):
    print(position, ".", song)

1 . Kesariya
2 . Apna Bana Le
3 . Tum Hi Ho
4 . Chaleya
5 . Heeriye
6 . O Maahi


3.
Given two lists — one of food items and one of prices — use zip() to print each food item with its price like a Zomato menu (e.g., 'Pizza - ₹250').

In [6]:
food_items = ["Pizza", "Burger", "Pasta", "Biryani", "Sandwich"]

prices = [250, 150, 200, 300, 120]

for food, price in zip(food_items, prices):
    print(food, "-", "₹" + str(price))

Pizza - ₹250
Burger - ₹150
Pasta - ₹200
Biryani - ₹300
Sandwich - ₹120



4.
Write a generator function called insta_posts_generator(posts) that takes a list of Instagram post captions and yields one caption at a time. Use next() to get and print the next post caption each time until all captions are printed.<br><br><em><strong>Hint:</strong> Use the yield keyword inside your function and handle StopIteration when all posts are done.</em>

In [7]:
def insta_posts_generator(posts):
    for post in posts:
        yield post


posts = [
    "Beautiful sunset ",
    "Weekend vibes!",
    "Best day ever ",
    "Travel memories "
]

post_generator = insta_posts_generator(posts)

try:
    while True:
        print(next(post_generator))
        
except StopIteration:
    print("All posts have been printed.")

Beautiful sunset 
Weekend vibes!
Best day ever 
Travel memories 
All posts have been printed.


5.
Build a generator function called cashback_generator(transactions) that takes a list of Paytm transaction amounts and yields 5% cashback for each transaction. Print out the cashback values for all transactions.

In [8]:
def cashback_generator(transactions):
    for amount in transactions:
        cashback = amount * 0.05
        yield cashback


transactions = [1000, 500, 2000, 750, 1500]

for cashback in cashback_generator(transactions):
    print("Cashback: ₹", cashback)

Cashback: ₹ 50.0
Cashback: ₹ 25.0
Cashback: ₹ 100.0
Cashback: ₹ 37.5
Cashback: ₹ 75.0


SESSION :- 17
1.
Use the math module to calculate the square root, factorial, and value of pi for given numbers, and print each result.

In [9]:
import math

number = 5

print("Square root:", math.sqrt(number))
print("Factorial:", math.factorial(number))
print("Value of Pi:", math.pi)

Square root: 2.23606797749979
Factorial: 120
Value of Pi: 3.141592653589793


2.
Write a script that lists all files in your current directory using the os module, and prints only those files with a .jpg or .png extension.<br><br><em><strong>Hint:</strong> Use os.listdir() and string methods to filter file names.</em>

In [ ]:
import os

files = os.listdir()

print("image files:" "C:\Users\JIYA\OneDrive\Pictures\Acer\mnb.jpg")

for file in files:
    if file.lower().endswith((".jpg", ".png")):
        print(file)

3.
Create a Python program that accepts a date in 'YYYY-MM-DD' format from the user and displays the day of the week using the datetime module.

In [10]:
from datetime import datetime

date_input = input("Enter date (YYYY-MM-DD): ")

try:
    date = datetime.strptime(date_input, "%Y-%m-%d")
    print("Day of the week:", date.strftime("%A"))

except ValueError:
    print("Invalid date format. Please use YYYY-MM-DD.")

Day of the week: Friday


4.
Build a simple custom module named insta_utils.py with a function format_follower_count(n) that returns '1.5K' for 1500 and '2.3M' for 2300000. Import and use this function in another script to display formatted counts for 3 sample numbers.

In [11]:
def format_follower_count(n):
    if n >= 1000000:
        return f"{n / 1000000:.1f}M"
    elif n >= 1000:
        return f"{n / 1000:.1f}K"
    else:
        return str(n)

In [12]:
numbers = [1500, 2300000, 850]

for number in numbers:
    print(number, "->", format_follower_count(number))

1500 -> 1.5K
2300000 -> 2.3M
850 -> 850


5.
Create a new virtual environment using venv, activate it, and install the statistics and requests packages via pip. Then, write a script that uses statistics.mean() to calculate the average of a list of numbers.

In [13]:
import statistics

numbers = [10, 20, 30, 40, 50]

average = statistics.mean(numbers)

print("Numbers:", numbers)
print("Average:", average)

Numbers: [10, 20, 30, 40, 50]
Average: 30


SESSION :- 18
1.
Use re.findall() to extract all valid Indian phone numbers (10 digits, starting with 7, 8, or 9) from a given text string that contains random numbers, prices, and phone numbers like those seen in OLX or WhatsApp chats.

In [14]:
import re

text = """
Contact numbers: 9876543210, 8123456789 and 9123456780.
Random numbers: 12345, 456789.
Prices: ₹999 and ₹2500.
"""

pattern = r'\b[789]\d{9}\b'

phone_numbers = re.findall(pattern, text)

print("Valid Indian phone numbers:")
print(phone_numbers)

Valid Indian phone numbers:
['9876543210', '8123456789', '9123456780']



2.
Write a Python function using re.search() that checks if a given string contains a valid date in the format DD/MM/YYYY (e.g., 25/06/2024), and returns True if found, otherwise False.<br><br><em><strong>Hint:</strong> Use the pattern '\b\d{2}/\d{2}/\d{4}\b'.</em>

In [15]:
import re

def check_date(text):
    pattern = r'\b\d{2}/\d{2}/\d{4}\b'

    if re.search(pattern, text):
        return True
    else:
        return False


print(check_date("My birthday is 25/06/2024"))
print(check_date("Today is 2024-06-25"))

True
False



3.
Given a messy text copied from a Zomato review containing multiple emails, use re.findall() to extract all valid email addresses and print them as a list.

In [16]:
import re

text = """
Great food! Contact restaurant@gmail.com for offers.
My email is jiya123@gmail.com.
For support, write to support@zomato.com.
"""

pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b'

emails = re.findall(pattern, text)

print("Email addresses:")
print(emails)

Email addresses:
['restaurant@gmail.com', 'jiya123@gmail.com', 'support@zomato.com']



4.
Use re.sub() to mask all but the last 4 digits of any phone number in a string (e.g., replace 9876543210 with ******3210) like Paytm does for privacy.<br><br><em><strong>Constraint:</strong> Do not use loops; achieve this only with re.sub().</em>

In [17]:
import re

text = "My phone number is 9876543210 and another number is 8123456789."

masked_text = re.sub(
    r'\b\d{10}\b',
    lambda m: '******' + m.group()[-4:],
    text
)

print(masked_text)

My phone number is ******3210 and another number is ******6789.



5.
Use ChatGPT to generate a regex pattern that matches Flipkart-style order IDs (e.g., OD123456789012345000) and test it in Python using re.search() on sample order strings.

In [18]:
import re

order_strings = [
    "Your order ID is OD123456789012345000",
    "Order: OD987654321098765432",
    "Invalid order: AB123456789012345000"
]

pattern = r'\bOD\d{18}\b'

for order in order_strings:
    result = re.search(pattern, order)

    if result:
        print("Order ID found:", result.group())
    else:
        print("No valid order ID found.")

Order ID found: OD123456789012345000
Order ID found: OD987654321098765432
No valid order ID found.


SESSION :- 19
1.
Define a Python class called Song with attributes title, artist, and duration (in seconds), and use the __init__() constructor to initialize these values when creating an object.

In [19]:
class Song:
    def __init__(self, title, artist, duration):
        self.title = title
        self.artist = artist
        self.duration = duration


song1 = Song("Kesariya", "Arijit Singh", 268)

print("Title:", song1.title)
print("Artist:", song1.artist)
print("Duration:", song1.duration, "seconds")

Title: Kesariya
Artist: Arijit Singh
Duration: 268 seconds



2.
Create an object of the Song class for your favorite track from Spotify, and print out its title and artist using object attributes.

In [20]:
class Song:
    def __init__(self, title, artist, duration):
        self.title = title
        self.artist = artist
        self.duration = duration


favorite_song = Song("Kesariya", "Arijit Singh", 268)

print("Song Title:", favorite_song.title)
print("Artist:", favorite_song.artist)

Song Title: Kesariya
Artist: Arijit Singh



3.
Add a method play_preview(self) to your Song class that prints 'Playing 30-second preview of [title] by [artist]'. Call this method for your Song object.

In [21]:
class Song:
    def __init__(self, title, artist, duration):
        self.title = title
        self.artist = artist
        self.duration = duration

    def play_preview(self):
        print("Playing 30-second preview of", self.title, "by", self.artist)


song1 = Song("Kesariya", "Arijit Singh", 268)

song1.play_preview()

Playing 30-second preview of Kesariya by Arijit Singh



4.
Create a class called FoodOrder with attributes restaurant_name, items (a list), and total_price. Add a method add_item(self, item, price) that adds the item to the items list and updates total_price. Demonstrate by creating a FoodOrder object and adding two items like you would on Zomato.

In [22]:
class FoodOrder:
    def __init__(self, restaurant_name):
        self.restaurant_name = restaurant_name
        self.items = []
        self.total_price = 0

    def add_item(self, item, price):
        self.items.append(item)
        self.total_price += price


order = FoodOrder("Pizza Hut")

order.add_item("Pizza", 250)
order.add_item("Garlic Bread", 120)

print("Restaurant:", order.restaurant_name)
print("Items:", order.items)
print("Total Price: ₹", order.total_price)

Restaurant: Pizza Hut
Items: ['Pizza', 'Garlic Bread']
Total Price: ₹ 370



5.
Refactor your Song class so that it also tracks a play_count attribute (starting at 0), and add a method increment_play_count(self) that increases play_count by 1 each time it's called. Show how you would use this to count how many times a user plays a song.<br><br><em><strong>Hint:</strong> Call increment_play_count() multiple times and print play_count to see the update.</em>

In [23]:
class Song:
    def __init__(self, title, artist, duration):
        self.title = title
        self.artist = artist
        self.duration = duration
        self.play_count = 0

    def increment_play_count(self):
        self.play_count += 1


song1 = Song("Kesariya", "Arijit Singh", 268)

song1.increment_play_count()
song1.increment_play_count()
song1.increment_play_count()

print("Song:", song1.title)
print("Artist:", song1.artist)
print("Play Count:", song1.play_count)

Song: Kesariya
Artist: Arijit Singh
Play Count: 3


SESSION :- 20
1.
Create a Python class called Product with a private attribute _price. Initialize _price in the constructor and write a method to display its value.

In [24]:
class Product:
    def __init__(self, price):
        self._price = price

    def display_price(self):
        print("Product Price: ₹", self._price)


product = Product(500)

product.display_price()

Product Price: ₹ 500



2.
Add getter and setter methods for the _price attribute in your Product class to safely access and update the price. Make sure the setter prevents setting a negative price.<br><br><em><strong>Hint:</strong> Raise a ValueError if the new price is less than zero.</em>

In [25]:
class Product:
    def __init__(self, price):
        self._price = price

    # Getter
    def get_price(self):
        return self._price

    # Setter
    def set_price(self, price):
        if price < 0:
            raise ValueError("Price cannot be negative.")
        self._price = price


product = Product(500)

print("Current Price: ₹", product.get_price())

product.set_price(750)

print("Updated Price: ₹", product.get_price())

Current Price: ₹ 500
Updated Price: ₹ 750



3.
Build a class called Playlist that has a private attribute _songs (a list of song names). Write methods to add a song, remove a song, and get the current list of songs using proper encapsulation.

In [26]:
class Playlist:
    def __init__(self):
        self._songs = []

    def add_song(self, song):
        self._songs.append(song)

    def remove_song(self, song):
        if song in self._songs:
            self._songs.remove(song)
        else:
            print("Song not found.")

    def get_songs(self):
        return self._songs.copy()


playlist = Playlist()

playlist.add_song("Kesariya")
playlist.add_song("Apna Bana Le")
playlist.add_song("Tum Hi Ho")

print("Playlist:", playlist.get_songs())

playlist.remove_song("Apna Bana Le")

print("Updated Playlist:", playlist.get_songs())

Playlist: ['Kesariya', 'Apna Bana Le', 'Tum Hi Ho']
Updated Playlist: ['Kesariya', 'Tum Hi Ho']



4.
Create an abstract class PaymentMethod with an abstract method pay(amount). Then, create two subclasses: UPI and CreditCard, each implementing the pay method with a print statement showing how the payment would be processed.<br><br><em><strong>Hint:</strong> Use the abc module for abstraction.</em>

In [27]:
from abc import ABC, abstractmethod


class PaymentMethod(ABC):

    @abstractmethod
    def pay(self, amount):
        pass


class UPI(PaymentMethod):

    def pay(self, amount):
        print("Processing UPI payment of ₹", amount)


class CreditCard(PaymentMethod):

    def pay(self, amount):
        print("Processing Credit Card payment of ₹", amount)


upi_payment = UPI()
card_payment = CreditCard()

upi_payment.pay(500)
card_payment.pay(1000)

Processing UPI payment of ₹ 500
Processing Credit Card payment of ₹ 1000


SESSION :- 21
1.
Create a Python class called Product with a method get_discount() that returns 0. Write a subclass called Electronics that overrides get_discount() to return 10.

In [28]:
class Product:
    def get_discount(self):
        return 0


class Electronics(Product):
    def get_discount(self):
        return 10


product = Product()
electronic = Electronics()

print("Product discount:", product.get_discount(), "%")
print("Electronics discount:", electronic.get_discount(), "%")

Product discount: 0 %
Electronics discount: 10 %



2.
Build a class FoodOrder with a method calculate_total() that returns the base price. Create a subclass ZomatoOrder that overrides calculate_total() to add a 5% delivery charge.

In [29]:
class FoodOrder:
    def __init__(self, base_price):
        self.base_price = base_price

    def calculate_total(self):
        return self.base_price


class ZomatoOrder(FoodOrder):
    def calculate_total(self):
        delivery_charge = self.base_price * 0.05
        return self.base_price + delivery_charge


order1 = FoodOrder(500)
order2 = ZomatoOrder(500)

print("Food Order Total: ₹", order1.calculate_total())
print("Zomato Order Total: ₹", order2.calculate_total())

Food Order Total: ₹ 500
Zomato Order Total: ₹ 525.0



3.
Write a function show_bonus(employee) that takes any object with a bonus() method and prints the result. Test it with two classes: Influencer (bonus returns 2000) and BrandManager (bonus returns 5000), demonstrating polymorphism.

In [30]:
class Influencer:
    def bonus(self):
        return 2000


class BrandManager:
    def bonus(self):
        return 5000


def show_bonus(employee):
    print("Bonus: ₹", employee.bonus())


influencer = Influencer()
brand_manager = BrandManager()

show_bonus(influencer)
show_bonus(brand_manager)

Bonus: ₹ 2000
Bonus: ₹ 5000



4.
Given this code: class User: def get_status(self): return 'active' class PremiumUser(User): pass. Update PremiumUser to override get_status() so it returns 'premium'. Then, create one User and one PremiumUser and print their statuses.<br><br><em><strong>Hint:</strong> Use the same method name in both classes to override.</em>

In [31]:
class User:
    def get_status(self):
        return "active"


class PremiumUser(User):
    def get_status(self):
        return "premium"


user = User()
premium_user = PremiumUser()

print("User status:", user.get_status())
print("Premium User status:", premium_user.get_status())

User status: active
Premium User status: premium
